### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by Nemikolh** [stackblitz/tutorialkit#144]
Hey there! 

Thanks for showing interest in using TutorialKit! We are currently planning to do a 1.0 release and we're excited to share a list of the changes that we are intending to make before the release.

#### Planned Changes

* [x] :rotating_light:  Renaming `tutorialkit` to `@tutorialkit/cli`. So we can use that name for the vscode extension and also because the `npm create tutorial` command is the recommended way to create a new tutorial.
  * https://github.com/stackblitz/tutorialkit/pull/153
* [x] :rotating_light: Renaming `@tutorialkit/components-react` to `@tutorialkit/react` and move it from `components/react` to `react`. Simpler name and descriptive enough.
  * https://github.com/stackblitz/tutorialkit/pull/155
* [x] :rotating_light: Update `src/content/config.ts` to import the full schema from `@tutorialkit/types`.
  * https://github.com/stackblitz/tutorialkit/pull/156
* [x] :rotating_light: UnoCSS config:
  * [x] Use a deep merge strategy and move default presets and transformers in `@tutorialkit/theme`.
    * https://github.com/stackblitz/tutorialkit/pull/270
  * [x] Find a way to remove `content.inline`
    * https://github.com/stackblitz/tutorialkit/pull/270
* [x] :book: Document docs on how tow write your own component with `tutorialkit:store`
  * https://github.com/stackblitz/tutorialkit/pull/348
* [x] :book: Document  that `tutorialkit:core` provide low level access to webcontainer and is to be used only as a last resort
  * https://github.com/stackblitz/tutorialkit/pull/348
* [x] :book: Document that using `@tutorialkit/react` without TutorialKit is experimental
  * https://github.com/stackblitz/tutorialkit/pull/346 
* [x] Have `create-tutorial` depend on `"@tutorialkit/cli": "latest"` and release a fire and forget version.
  * https://github.com/stackblitz/tutorialkit/pull/146
* [x] Remove `.vscode/settings.json`.
  * https://github.com/stackblitz/tutorialkit/pull/173
* [x] Add TutorialKit extension to the list of recommended extension in the generated template.
  * https://github.com/stackblitz/tutorialkit/pull/172
* [x] Extension: 
  * [x] Frontmatter autocomplete:
    * #143 
  * [x] Support folder-based and config-based ordering
    * #223
  * [x] Part, chapter, lesson deletion
    * #223

#### Nice to have, some post 1.0.0 launch:

* [ ] Have the default tutorial generated showcase all of the features of TutorialKit (ala [slidev](https://github.com/slidevjs/slidev))
* [x] JSDocs on `TutorialStore` class
* [ ] VSCode Extension
  * [ ] Automated releases
  * [ ] Inheritance information
  * [ ] Drag and drop ordering for lesson / chapter / parts
* [ ] "Checks" to prevent navigation to next lesson until current checks have passed
* [ ] Syntax highlighting for
  * [x] Vue
    * #256 
  * [x] Svelte
    * #212 
  * [ ] Astro
* [ ] Monaco as an alternative option to CodeMirror
* [ ] Opt-in TypeScript intellisense

**Comment by Barbapapazes** [comment]
For the UnoCSS part, a similar solution to this one, https://github.com/slidevjs/slidev/blob/main/packages/slidev/node/setups/unocss.ts, used in Slidev could be used? This could help to simplify the DX and the starter.

**Comment by Nemikolh** [comment]
@Barbapapazes Thanks for the pointer! This `mergeConfigs` function from `unocss` seems to be what we're looking for 👀
